//fetch product
export const FETCH_PRODUCT_REQUEST = 'FETCH_PRODUCT_REQUEST';
export const FETCH_PRODUCT_SUCCESS = 'FETCH_PRODUCT_SUCCESS';
export const FETCH_PRODUCT_FAILURE = 'FETCH_PRODUCT_FAILURE';

//post product
export const FETCH_POST_PRODUCT_REQUEST = 'FETCH_POST_PRODUCT_REQUEST';
export const FETCH_POST_PRODUCT_SUCCESS = 'FETCH_POST_PRODUCT_SUCCESS';
export const FETCH_POST_PRODUCT_FAILURE = 'FETCH_POST_PRODUCT_FAILURE';